import { useEffect, useRef } from 'react';
import { Icon } from './DashboardShell';

export function Toast({ toast, onClose }) {
  useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(onClose, 3000); return () => window.clearTimeout(timer); }, [toast, onClose]);
  if (!toast) return null;
  return <div role="status" className="dashboard-toast fixed bottom-5 right-5 z-[70] flex max-w-sm items-start gap-3 rounded-2xl border border-green-100 bg-white p-4 shadow-2xl"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-green-100 font-bold text-green-600">✓</span><div><b className="block text-sm text-[#17213a]">{toast.title}</b><p className="mt-0.5 text-sm text-slate-500">{toast.message}</p></div><button onClick={onClose} className="ml-2 text-slate-400" aria-label="Dismiss notification">×</button></div>;
}

const Button = ({ children, outline, className = '', ...props }) => <button {...props} className={`${outline ? 'border border-slate-200 text-slate-700' : 'bg-brand-500 text-white'} interactive rounded-xl px-4 py-2.5 text-sm font-semibold ${className}`}>{children}</button>;
function Notifications() { return <><h2 className="text-2xl font-bold">Notifications</h2><div className="mt-5 divide-y divide-slate-100">{[['New Head Chef job', 'Matching your profile in Kolkata', '10 minutes ago'], ['New message', 'Spice Garden Team', '1 hour ago'], ['Application update', 'You have been shortlisted', 'Yesterday']].map(([title, text, time]) => <article className="flex gap-3 py-4" key={title}><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-brand-500"/><div><b className="block text-sm">{title}</b><p className="text-sm text-slate-500">{text}</p><time className="text-xs text-slate-400">{time}</time></div></article>)}</div></>; }

export function DashboardPopup({ popup, onClose, onAction }) {
  const dialogRef = useRef(null);
  const touchStart = useRef(null);
  useEffect(() => { if (!popup) return undefined; const escape = event => event.key === 'Escape' && onClose(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', escape); window.setTimeout(() => dialogRef.current?.querySelector('button, input, [tabindex]:not([tabindex="-1"])')?.focus(), 0); return () => { document.body.style.overflow = overflow; window.removeEventListener('keydown', escape); }; }, [popup, onClose]);
  if (!popup) return null;
  const item = popup.payload || {};
  let content;
  if (popup.type === 'job') content = <><img src={item.image} alt={`${item.company} restaurant`} className="h-40 w-full rounded-2xl object-cover"/><p className="mt-5 text-sm font-semibold text-brand-600">{item.company} · Verified</p><h2 className="mt-1 text-2xl font-bold">{item.title}</h2><p className="mt-4 text-sm text-slate-600">{item.location} · {item.experience}</p><p className="mt-2 font-semibold">{item.salary} / month</p><div className="mt-4 flex flex-wrap gap-2">{item.tags?.map(tag => <span className="rounded-full bg-orange-50 px-3 py-1 text-xs text-brand-600" key={tag}>{tag}</span>)}</div><h3 className="mt-5 font-bold">About this role</h3><p className="mt-2 text-sm leading-6 text-slate-600">Looking for an experienced chef to lead the kitchen team and maintain food quality.</p><div className="mt-6 flex gap-3"><Button onClick={() => onAction('apply', item)}>Apply now</Button><Button outline onClick={() => onAction('save', item)}>Save job</Button></div></>;
  else if (popup.type === 'apply') content = <div className="text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-orange-100 text-xl text-brand-600">✓</span><h2 className="mt-4 text-2xl font-bold">Apply for this job?</h2><p className="mt-3 font-semibold">{item.title} — {item.company}</p><p className="mt-2 text-sm text-slate-500">Your profile will be sent to the restaurant.</p><div className="mt-6 flex justify-center gap-3"><Button outline onClick={onClose}>Cancel</Button><Button onClick={() => onAction('confirm-apply', item)}>Apply now</Button></div></div>;
  else if (popup.type === 'application') content = <><h2 className="text-2xl font-bold">Application Details</h2><p className="mt-3 font-semibold">{item.title}</p><p className="text-sm text-slate-500">{item.company}</p><p className="mt-4 text-sm">Applied: {item.date}</p><p className="mt-2 text-sm font-semibold text-brand-600">● {item.status}</p><div className="mt-6 space-y-3 border-l-2 border-orange-100 pl-4 text-sm"><p>✓ Application submitted</p><p>✓ Profile viewed</p><p className="font-semibold text-brand-600">● Under review</p><p className="text-slate-400">○ Interview</p><p className="text-slate-400">○ Final decision</p></div></>;
  else if (popup.type === 'stats') content = <><h2 className="text-2xl font-bold">{item.title}</h2><p className="mt-2 text-slate-500">{item.total}</p><div className="mt-6 space-y-3">{item.rows?.map(([label, value]) => <p className="flex justify-between text-sm" key={label}><span>{label}</span><b>{value}</b></p>)}</div><Button className="mt-6" onClick={() => onAction(item.action)}>View details</Button></>;
  else if (popup.type === 'profile') content = <><h2 className="text-2xl font-bold">Complete Your Profile</h2><p className="mt-2 text-slate-500">Your profile is 85% complete.</p><div className="mt-5 space-y-3 text-sm"><p>✓ Basic information</p><p>✓ Experience</p><p>✓ Skills</p><p>✓ Cuisine specialties</p><p className="text-slate-400">○ Portfolio</p><p className="text-slate-400">○ Certifications</p></div><Button className="mt-6" onClick={() => onAction('profile-page')}>Complete Profile</Button></>;
  else if (popup.type === 'message') content = <><h2 className="text-xl font-bold">{item.name} <span className="text-xs font-normal text-green-600">● Online</span></h2><div className="mt-5 min-h-40 space-y-3 rounded-xl bg-slate-50 p-4 text-sm"><p className="w-fit rounded-2xl bg-white px-3 py-2 shadow-sm">Hi, are you available for an interview this week?</p><p className="ml-auto w-fit rounded-2xl bg-brand-500 px-3 py-2 text-white">I'd be happy to discuss it.</p></div><form onSubmit={event => { event.preventDefault(); onAction('message-sent'); }} className="mt-4 flex gap-2"><input required className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5" placeholder="Type a message..."/><Button>Send</Button></form></>;
  else if (popup.type === 'update') content = <><p className="font-semibold text-brand-600">New opportunity</p><h2 className="mt-2 text-2xl font-bold">{item.title}</h2><p className="mt-2 text-slate-600">A position matching your profile was posted in Kolkata.</p><p className="mt-5 text-sm"><b>Salary:</b> {item.salary} / month<br/><b>Experience:</b> {item.experience}</p><Button className="mt-6" onClick={() => onAction('job', item)}>View Job</Button></>;
  else if (popup.type === 'motivation') content = <div className="text-center"><h2 className="text-2xl font-bold">Great chefs build great restaurants.</h2><p className="mt-4 text-sm leading-6 text-slate-600">Keep improving your profile, learning new cuisines, and applying to the right opportunities.</p><p className="mt-3 font-semibold text-brand-600">Keep cooking. Keep growing.</p><Button className="mt-6" onClick={() => onAction('discover')}>Explore Jobs</Button></div>;
  else if (popup.type === 'profile-menu') content = <><div className="border-b border-slate-100 pb-4"><h2 className="text-xl font-bold">Akas Maji</h2><p className="text-sm text-slate-500">Chef · Verified</p></div><div className="mt-3 grid gap-1"><Button outline className="text-left" onClick={() => onAction('profile-page')}>My Profile</Button><Button outline className="text-left" onClick={onClose}>Account Settings</Button><Button outline className="text-left" onClick={onClose}>Notifications</Button></div></>;
  else content = <Notifications/>;
  const trapFocus = event => { if (event.key !== 'Tab') return; const nodes = [...dialogRef.current.querySelectorAll('button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])')]; if (!nodes.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-[#10182f]/45 p-0 backdrop-blur-[3px] sm:items-center sm:p-5" onMouseDown={event => event.target === event.currentTarget && onClose()}><section ref={dialogRef} role="dialog" aria-modal="true" aria-label="Dashboard dialog" onKeyDown={trapFocus} onTouchStart={event => { touchStart.current = event.touches[0].clientY; }} onTouchEnd={event => { if (touchStart.current && event.changedTouches[0].clientY - touchStart.current > 85) onClose(); touchStart.current = null; }} className="dashboard-modal relative max-h-[90vh] w-full overflow-y-auto rounded-t-[24px] bg-white p-6 shadow-2xl sm:max-w-lg sm:rounded-[24px]"><div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-slate-200 sm:hidden"/><button onClick={onClose} aria-label="Close popup" className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-slate-500"><Icon name="x" className="h-4 w-4"/></button>{content}</section></div>;
}
